version: '3.4'

services:
  Django:
    image: django_inmuebles
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
